### ISSUE TITLE
Tests not finishing

### ISSUE THREAD

**Issue by Hainish** [EFForg/cover-your-tracks#19]
We've had various reports of the tests not finishing with various different addon combinations. Creating a master ticket for this.

**Comment by Hainish** [comment]
This should be solved for uBlock as of https://github.com/EFForg/panopticlick-python/commit/08c724c9b6f208dd93022c6be98e8f8afcd686b9

**Comment by andresbase** [comment]
New report using Safari 11.0.3 with Ublock Origin and AdGuard where it will hang on the final test.

**Comment by Rode-Ven** [comment]
Tests also fail when [Pi-Hole](https://github.com/pi-hole/) is active on the network where the tested machine is connected to.

I can confirm that Pi-Hole with standard blocklists prevents access to the following domains used by panopticlick:
- trackersimulator.org
- eviltracker.net
- do-not-tracker.org

This causes panopticlick's tests to fail after a few page refreshes with an error ("This site can’t be reached") when trying to opening an URL like:
   https://eviltracker.net/tracker-reporting-nojs?a=
where the domain seems to be randomly picked from a list including at least the three mentioned above. Test execution thus stops completely.

In consequence, panopticlick is not able to present the user with any test results at all. 

I guess one could make the tests run by whitelisting the domains in Pi-Hole, but that'd somehow defeat the purpose of testing, wouldn't it?
