### ISSUE TITLE
Add support for timeZone string

### ISSUE THREAD

**Issue by Hainish** [EFForg/cover-your-tracks#21]
Specifically, `Intl.DateTimeFormat().resolvedOptions().timeZone`

When we last did a development push on the fingerprinting metrics, browsers lacked support for "computed timeZone"

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions

> Hi,
>
> You're likely aware of this, but the *value* result for time zone currently
> displays an integer (*240*), which is the UTC offset in minutes. Wouldn't
> the fingerprinting test have more specificity if it used
> *intl.datetimeformat().resolvedoptions().timezone* (when supported) since
> the result (*America/New_York*) is a string identifying a city?

**Comment by sm-Fifteen** [comment]
I'm seeing this come up in the list of detailled fingerprinting information, and it looks like it's been implemented upstream by fingerprintjs/fingerprintjs2#364 2 years ago. Wouldn't that mean this issue has been resolved?
