### ISSUE TITLE
Direct users to https://privacybadger.org/ when recommending Privacy Badger

### ISSUE THREAD

**Issue by ghostwords** [EFForg/cover-your-tracks#51]
Instead of offering the direct download/extension store listing link on Panopticlick, we should simply have the big "Get Privacy Badger" button link to https://privacybadger.org/.

We should avoid reimplementing privacybadger.org's browser detection logic, and instead rely on Privacy Badger's homepage to direct the user to the appropriate destination.

**Comment by Hainish** [comment]
Panopticlick makes recommendations already based on the Browser / OS you have installed.  If you are running a browser or OS that doesn't offer Privacy Badger, we make other recommendations.  Ideally, we should mirror this detection logic between the projects, and Privacy Badger should act on some subset of the detected result, while Panopticlick should make some recommendation in all scenarios.

Who implemented the browser detection logic on that page?  We probably want to abstract that logic into its own repo.

**Comment by ghostwords** [comment]
Privacy Badger homepage browser detection logic lives in https://github.com/EFForg/privacybadger-website/blob/master/assets/js/download.js

Agreed we should reuse browser detection logic between EFF projects. We've had multiple bugs with it when it was seemingly implemented from scratch for the new Privacy Badger homepage ([one open bug still remaining](https://github.com/EFForg/privacybadger-website/issues/71)).

**Comment by ghostwords** [comment]
To add to the above, while I agree that browser detection logic should be shared, I still think that for supported browseres, Panopticlick should direct users on to the [Privacy Badger homepage](https://privacybadger.org/) instead of offering direct download links on Panopticlick.

**Comment by ghostwords** [comment]
Does Cover Your Tracks no longer try to offer a user agent-dependent Privacy Badger recommendation? Maybe as of https://github.com/EFForg/cover-your-tracks/commit/68cba8a8f076ca5129b8bc90076de92e54de94ce#diff-bf9a17f0457225b1ab7281a6071a816ddd4c311d5aae7d673a81ceb70678c3b3? This can be closed then.

**Comment by ghostwords** [comment]
I still see code references ([1](https://github.com/EFForg/cover-your-tracks/blob/fa39cf9fca22ed28e242f7982ae34653605b84c9/util.py#L71-L74), [2](https://github.com/EFForg/cover-your-tracks/blob/eb9d59c7e86bfad62d4779251356ea6ed0354044/main.py#L340-L341)) but maybe they are no longer used? They look to be out of date: Privacy Badger supports Opera, Firefox for Android, the new Chromium-based Edge, ...
